sudo: required
language: ruby
addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck
    - findutils
install:
  - sudo apt-get install unzip
  - wget https://releases.hashicorp.com/packer/0.12.0/packer_0.12.0_linux_amd64.zip
  - sudo unzip packer_0.12.0_linux_amd64.zip -d /usr/local/bin/
script:
  - make ci
