version: 0.2

phases:
  install:
    commands:
      - make deps
  pre_build:
    commands:
      - make config-examples-$AEM_VERSION-$OS_TYPE
  build:
    commands:
      - make $COMPONENT version=$CODEBUILD_SOURCE_VERSION
  post_build:
    commands:
      - make ami-ids config_path=stage/user-config/
artifacts:
  files:
    - stage/*-stack-builder-ami-ids.json
