---
version: 5

hierarchy:
  - name: OS family, name and major release
    path: "%{::os.family}/%{::os.name}-%{::os.release.major}.yaml"

  - name: OS family and name
    path: "%{::os.family}/%{::os.name}.yaml"

  - name: Common
    path: common.yaml
