---
version: 4
datadir: data
hierarchy:
  - name: YAML
    paths: [
      "%{::os.family}/%{::os.name}-%{::os.release.major}",
      "%{::os.family}/%{::os.name}",
      common,
    ]
    backend: yaml
