---
:backends: yaml
:yaml:
  :datadir: data
:hierarchy:
  - local
  - "%{::os.family}/%{::os.name}-%{::os.release.major}"
  - "%{::os.family}/%{::os.name}"
  - "%{::packer_build_name}"
  - common
:logger: noop
:merge_behavior: native
:deep_merge_options: {}
