---
timezone::region: 'Australia'
timezone::locality: 'Melbourne'

cloudwatchlogs::region: 'ap-southeast-2'

base::python_package: python
base::python_pip_package: python-pip
base::python_cheetah_package: python-cheetah

base::aws_agents_install_url: 'https://d1wk0tztpsntt1.cloudfront.net/linux/latest/install'

base::tmp_dir: "%{hiera('tmp_dir')}"
