---
timezone::region: 'Australia'
timezone::locality: 'Melbourne'

cloudwatchlogs::region: 'ap-southeast-2'

base::aws_agents_install_url: 'https://d1wk0tztpsntt1.cloudfront.net/linux/latest/install'
