---
- name: Create AWS CodeBuild projects for creating machine images for various combination of AEM versions and OS types
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    platform_types: [aws]
    aem_versions: [aem62, aem63, aem64]
    os_types: [rhel7]
    components: [java, dispatcher, author, publish, dispatcher, author-publish-dispatcher]

  tasks:

    - name: Delete CodeBuild projects
      shell: |
        aws codebuild delete-project \
        --name {{ item[0] }}-{{ item[1] }}-{{ item[2] }}-{{ item[3] }} \
        --region {{ aws.region }}
      with_nested:
        - "{{ platform_types }}"
        - "{{ aem_versions }}"
        - "{{ os_types }}"
        - "{{ components }}"
